export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Herzlich Willkommen',
    headline: 'Bei uns finden Sie für jeden Anlass das passende Geschenk.',
    description: ['Spirituosen, Liköre, Wein, Essige, Öle, Feinkost, Dips, Gewürzmischungen, Pasta, Pesto, Fruchtaufstriche, Tee, Pralinen, Schokoladen, Deko und vieles mehr...',
                    <br/>,
                    <br/>,
                    'Am 1.7.2008 haben wir, Silvia und Martin Dupont, das 1. Feinkost-Deko-Geschenke-Geschäft in Hermeskeil, Rosenweg 12, eröffnet.'],
    buttonLabel: 'Get started',
    imgStart: false,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Vor Ort',
    headline: 'DHL-Paketshop',
    description: ['-Pakete, Päckchen, Retouren abgeben.',
                    <br/>, 
                    '-Briefmarken, Paketmarken kaufen.',
                    <br/>,
                    '-Paket/ Retouren label drucken',
                    <br/>,
                    <br/>,
                    '-Pakete zu uns senden lassen:',
                    <br/>,
                    '1) auf ', <a href="https://www.paket.de" target="_blank" rel="noopener noreferrer">www.paket.de</a>, ' registrieren',
                    <br/>,
                    '2) Straßen Name: 422 LebensArt Hermeskeil'
                ],
    buttonLabel: 'Lern More',
    imgStart: true,
    //img: require('../../images/undraw_deliveries_131a.svg').default,
    alt: 'Piggybank',
    dark: false,
    primary: false,
    darkText: true
};

export const homeObjNews = {
    id: 'news',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'News',
    headline: 'Neues',
    description: [
        <strong>Corona-Situation</strong>,
        <br/>,
        'Wir haben geöffnet!',
        <br/>,
        'Entsprechende Hygienevorkehrungen sind getroffen.',
        <br/>,
        'Halten Sie bitte Abstand.',
        <br/>,
        'Mundschutz- /Nasenbedeckungen ausschließlich OP-Masken und FFP2-Masken tragen!',
        <br/>,
        'Vielen Dank für Ihr Verständnis.',
        <br/>,
        'Bleiben Sie gesund!',
        <br/>,
        <br/>,
        <br/>,
        <strong>Gewürze im Rohr</strong>,
        <br/>, 
        '-ohne Geschmacksverstärker',
        <br/>, 
        '-ohne Konservierungsstoffe',
        <br/>, 
        '-ohne Schnick-Schnack'
    ],
    imgStart: true,
    alt: 'Bild über Neuigkeiten',
    dark: true,
    primary: false,
    darkText: false
};